trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      curl -sSL https://releases.hashicorp.com/terraform/1.8.0/terraform_1.8.0_linux_amd64.zip -o terraform.zip
      unzip terraform.zip
      sudo mv terraform /usr/local/bin/
    displayName: 'Install Terraform'

  - script: |
      terraform version
      terraform init
    displayName: 'Terraform Init'

  - script: |
      terraform plan -out=tfplan
    displayName: 'Terraform Plan'

  - script: |
      terraform apply -auto-approve tfplan
    displayName: 'Terraform Apply'
