trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: '1.8.0'

steps:
  - task: UseTerraform@0
    inputs:
      terraformVersion: '$(TF_VERSION)'

  - script: |
      terraform init
    displayName: 'Terraform Init'

  - script: |
      terraform plan -out=tfplan
    displayName: 'Terraform Plan'

  - script: |
      terraform apply -auto-approve tfplan
    displayName: 'Terraform Apply'
